imports:
  - php

tools:
  external_code_coverage:
    timeout: 2100

  php_sim: false
  php_cpd: false

filter:
  paths:
    - 'src/*'

build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis

  tests:
    override:
      - command: 'php -v'
