name: test

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.gitattributes'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.gitattributes'
      - '.gitignore'

jobs:
  test:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [7.4, 8.0, 8.1, 8.2, 8.3, 8.4]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          extensions: curl, intl, pdo, pdo_sqlite, memcached
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Install composer with dev dependencies
        run: composer update --optimize-autoloader --classmap-authoritative --prefer-dist --no-progress --no-interaction --ansi

      - name: phpunit test
        run: composer phpunit
